title: Walansky (Wally) Richmond
logo: /headshot_circle.png
decription: Welcome to my portfolio, for any contact information please go to the following link [Here](https://linktr.ee/wallyrich)
#show_downloads: true
theme: jekyll-theme-minimal
